### PR TITLE
tls: tmp disable for hosts that fail STARTTLS

### LINKED ISSUE #770: disable TLS negotiation for remotes that fail STARTTLS
# the idea

If a remote attempts to connect and fails, cache their IP in an in-memory no-tls object. The next time that IP connects:

* don't offer STARTTLS
* remove their IP from the no-tls object

This would:

* permit mail to make it though from MTAs and MUAs with old/broken SSL/TLS implementations
* permit Haraka to require more secure TLS settings with less impact
* automatically enable TLS when those hosts fix/upgrade their TLS

### PR DESCRIPTION
**Pull request by msimerson**
fixes #770 

* disabled by default
* progressive enhancement: does nothing if redis unavailable.

### CODE REVIEW

File: plugins/tls.js [hunk 1]
```diff
@@ -67,16 +68,50 @@ exports.tls_capabilities = function (next, connection) {
...
 
-    /* Let the plugin chain continue. */
-    next();
+    redis.get(dbkey, function (err, dbr) {
+        if (err) {
+            connection.results.add(plugin, {err: err});
+            return enable_tls();
+        }
+
+        if (dbr === null) {
```
Comment (smfreegard) [inline plugins/tls.js]: Given that there's a PR to merge in ioredis instead of node-redis, you'd be better off doing this:  if (!dbr) otherwise this won't work if we change to ioredis later as it returns an empty string instead of null.

Comment (msimerson) [inline plugins/tls.js]: suggested change is made.
